config/routes.rb
Rails.application.routes.draw do
  
  get 'result_infos/redirect_to_new'
  get 'result_infos/select'
  post 'result_infos/create'
  resources :result_infos
  resources :subject_infos
  resources :exam_infos
  post 'attendence_infos/update'
  resources :attendence_infos
  resources :class_infos
  resources :student_infos

end

app/models/student_info.rb
class StudentInfo < ActiveRecord::Base
end

app/controllers/student_infos_controller.rb
class StudentInfosController < ApplicationController
  before_action :set_student_info, only: [:show, :edit, :update, :destroy]

  # GET /student_infos
  # GET /student_infos.json
  def index
    @student_infos = StudentInfo.all
  end

  # GET /student_infos/1
  # GET /student_infos/1.json
  def show
  end

  # GET /student_infos/new
  def new
    @student_info = StudentInfo.new
  end

  # GET /student_infos/1/edit
  def edit
  end

  # POST /student_infos
  # POST /student_infos.json
  def create
    @student_info = StudentInfo.new(student_info_params)

    respond_to do |format|
      if @student_info.save
        format.html { redirect_to @student_info, notice: 'Student info was successfully created.' }
        format.json { render :show, status: :created, location: @student_info }
      else
        format.html { render :new }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_infos/1
  # PATCH/PUT /student_infos/1.json
  def update
    respond_to do |format|
      if @student_info.update(student_info_params)
        format.html { redirect_to @student_info, notice: 'Student info was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_info }
      else
        format.html { render :edit }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_infos/1
  # DELETE /student_infos/1.json
  def destroy
    @student_info.destroy
    respond_to do |format|
      format.html { redirect_to student_infos_url, notice: 'Student info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_info
      @student_info = StudentInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_info_params
      params.require(:student_info).permit(:student_id, :student_name, :referenced_class_id)
    end
end

app/helpers/student_infos_helper.rb
module StudentInfosHelper
end

app/views/student_infos/_form.html.erb
<%= form_for(@student_info) do |f| %>
  <% if @student_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_info.errors.count, "error") %> prohibited this student_info from being saved:</h2>

      <ul>
      <% @student_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :referenced_class_id %><br>
    <%= f.collection_select(:referenced_class_id, ClassInfo.all, :class_id, :class_name, {}, { :multiple => false }) %>
	
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_infos/edit.html.erb
<h1>Editing Student Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_info %> |
<%= link_to 'Back', student_infos_path %>

app/views/student_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Infos</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Student name</th>
      <th>Referenced class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_infos.each do |student_info| %>
      <tr>
        <td><%= student_info.student_id %></td>
        <td><%= student_info.student_name %></td>
        <td><%= student_info.referenced_class_id %></td>
        <td><%= link_to 'Show', student_info %></td>
        <td><%= link_to 'Edit', edit_student_info_path(student_info) %></td>
        <td><%= link_to 'Destroy', student_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student info', new_student_info_path %>

app/views/student_infos/new.html.erb
<h1>New Student Info</h1>

<%= render 'form' %>

<%= link_to 'Back', student_infos_path %>

app/views/student_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_info.student_id %>
</p>

<p>
  <strong>Student name:</strong>
  <%= @student_info.student_name %>
</p>

<p>
  <strong>Referenced class:</strong>
  <%= @student_info.referenced_class_id %>
</p>

<%= link_to 'Edit', edit_student_info_path(@student_info) %> |
<%= link_to 'Back', student_infos_path %>