config/routes.rb
Rails.application.routes.draw do
  
  get 'result_infos/redirect_to_new'
  get 'result_infos/select'
  post 'result_infos/create'
  resources :result_infos
  resources :subject_infos
  resources :exam_infos
  post 'attendence_infos/update'
  resources :attendence_infos
  resources :class_infos
  resources :student_infos

end

app/models/subject_info.rb
class SubjectInfo < ActiveRecord::Base
end

app/controllers/subject_infos_controller.rb
class SubjectInfosController < ApplicationController
  before_action :set_subject_info, only: [:show, :edit, :update, :destroy]

  # GET /subject_infos
  # GET /subject_infos.json
  def index
    @subject_infos = SubjectInfo.order('exam_id').all

  end

  # GET /subject_infos/1
  # GET /subject_infos/1.json
  def show
  end

  # GET /subject_infos/new
  def new
    @subject_info = SubjectInfo.new
  end

  # GET /subject_infos/1/edit
  def edit
  end

  # POST /subject_infos
  # POST /subject_infos.json
  def create
    @subject_info = SubjectInfo.new(subject_info_params)

    respond_to do |format|
      if @subject_info.save
        format.html { redirect_to @subject_info, notice: 'Subject info was successfully created.' }
        format.json { render :show, status: :created, location: @subject_info }
      else
        format.html { render :new }
        format.json { render json: @subject_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subject_infos/1
  # PATCH/PUT /subject_infos/1.json
  def update
    respond_to do |format|
      if @subject_info.update(subject_info_params)
        format.html { redirect_to @subject_info, notice: 'Subject info was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_info }
      else
        format.html { render :edit }
        format.json { render json: @subject_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_infos/1
  # DELETE /subject_infos/1.json
  def destroy
    @subject_info.destroy
    respond_to do |format|
      format.html { redirect_to subject_infos_url, notice: 'Subject info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_info
      @subject_info = SubjectInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_info_params
      params.require(:subject_info).permit(:subject_id, :subject_name, :exam_id, :maximum_marks)
    end
end

app/helpers/subject_infos_helper.rb
module SubjectInfosHelper
end

app/views/subject_infos/_form.html.erb
<%= form_for(@subject_info) do |f| %>
  <% if @subject_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject_info.errors.count, "error") %> prohibited this subject_info from being saved:</h2>

      <ul>
      <% @subject_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="field">
    <%= f.label :subject_name %><br>
    <%= f.text_field :subject_name %>
  </div>
  <div class="field">
    <%= f.label :exam_id %><br>
    <%= f.collection_select(:exam_id, ExamInfo.all, :exam_id, :exam_name, {}, { :multiple => false }) %>

  </div>
  <div class="field">
    <%= f.label :maximum_marks %><br>
    <%= f.number_field :maximum_marks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subject_infos/edit.html.erb
<h1>Editing Subject Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject_info %> |
<%= link_to 'Back', subject_infos_path %>

app/views/subject_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subject Infos</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Subject name</th>
      <th>Exam</th>
      <th>Maximum marks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_infos.each do |subject_info| %>
      <tr>
        <td><%= subject_info.subject_id %></td>
        <td><%= subject_info.subject_name %></td>
        <td><%= subject_info.exam_id %></td>
        <td><%= subject_info.maximum_marks %></td>
        <td><%= link_to 'Show', subject_info %></td>
        <td><%= link_to 'Edit', edit_subject_info_path(subject_info) %></td>
        <td><%= link_to 'Destroy', subject_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject info', new_subject_info_path %>

app/views/subject_infos/new.html.erb
<h1>New Subject Info</h1>

<%= render 'form' %>

<%= link_to 'Back', subject_infos_path %>

app/views/subject_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @subject_info.subject_id %>
</p>

<p>
  <strong>Subject name:</strong>
  <%= @subject_info.subject_name %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @subject_info.exam_id %>
</p>

<p>
  <strong>Maximum marks:</strong>
  <%= @subject_info.maximum_marks %>
</p>

<%= link_to 'Edit', edit_subject_info_path(@subject_info) %> |
<%= link_to 'Back', subject_infos_path %>