config/routes.rb
Rails.application.routes.draw do
  
  get 'result_infos/redirect_to_new'
  get 'result_infos/select'
  post 'result_infos/create'
  resources :result_infos
  resources :subject_infos
  resources :exam_infos
  post 'attendence_infos/update'
  resources :attendence_infos
  resources :class_infos
  resources :student_infos

end

app/models/exam_info.rb
class ExamInfo < ActiveRecord::Base
end

app/controllers/exam_infos_controller.rb
class ExamInfosController < ApplicationController
  before_action :set_exam_info, only: [:show, :edit, :update, :destroy]

  # GET /exam_infos
  # GET /exam_infos.json
  def index
    @exam_infos = ExamInfo.all
  end

  # GET /exam_infos/1
  # GET /exam_infos/1.json
  def show
  end

  # GET /exam_infos/new
  def new
    @exam_info = ExamInfo.new
  end

  # GET /exam_infos/1/edit
  def edit
  end

  # POST /exam_infos
  # POST /exam_infos.json
  def create
    @exam_info = ExamInfo.new(exam_info_params)

    respond_to do |format|
      if @exam_info.save
        format.html { redirect_to @exam_info, notice: 'Exam info was successfully created.' }
        format.json { render :show, status: :created, location: @exam_info }
      else
        format.html { render :new }
        format.json { render json: @exam_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exam_infos/1
  # PATCH/PUT /exam_infos/1.json
  def update
    respond_to do |format|
      if @exam_info.update(exam_info_params)
        format.html { redirect_to @exam_info, notice: 'Exam info was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam_info }
      else
        format.html { render :edit }
        format.json { render json: @exam_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exam_infos/1
  # DELETE /exam_infos/1.json
  def destroy
    @exam_info.destroy
    respond_to do |format|
      format.html { redirect_to exam_infos_url, notice: 'Exam info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam_info
      @exam_info = ExamInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_info_params
      params.require(:exam_info).permit(:exam_id, :exam_name, :class_id)
    end
end

app/helpers/exam_infos_helper.rb
module ExamInfosHelper
end

app/views/exam_infos/_form.html.erb
<%= form_for(@exam_info) do |f| %>
  <% if @exam_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam_info.errors.count, "error") %> prohibited this exam_info from being saved:</h2>

      <ul>
      <% @exam_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exam_id %><br>
    <%= f.number_field :exam_id %>
  </div>
  <div class="field">
    <%= f.label :exam_name %><br>
    <%= f.text_field :exam_name %>
  </div>
  <div class="field">
    <%= f.label :class_id %><br>
    <%= f.collection_select(:class_id, ClassInfo.all, :class_id, :class_name, {}, { :multiple => false }) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exam_infos/edit.html.erb
<h1>Editing Exam Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam_info %> |
<%= link_to 'Back', exam_infos_path %>

app/views/exam_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exam Infos</h1>

<table>
  <thead>
    <tr>
      <th>Exam</th>
      <th>Exam name</th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exam_infos.each do |exam_info| %>
      <tr>
        <td><%= exam_info.exam_id %></td>
        <td><%= exam_info.exam_name %></td>
        <td><%= exam_info.class_id %></td>
        <td><%= link_to 'Show', exam_info %></td>
        <td><%= link_to 'Edit', edit_exam_info_path(exam_info) %></td>
        <td><%= link_to 'Destroy', exam_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam info', new_exam_info_path %>

app/views/exam_infos/new.html.erb
<h1>New Exam Info</h1>

<%= render 'form' %>

<%= link_to 'Back', exam_infos_path %>

app/views/exam_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exam:</strong>
  <%= @exam_info.exam_id %>
</p>

<p>
  <strong>Exam name:</strong>
  <%= @exam_info.exam_name %>
</p>

<p>
  <strong>Class:</strong>
  <%= @exam_info.class_id %>
</p>

<%= link_to 'Edit', edit_exam_info_path(@exam_info) %> |
<%= link_to 'Back', exam_infos_path %>