config/routes.rb
Rails.application.routes.draw do
  
  get 'result_infos/redirect_to_new'
  get 'result_infos/select'
  post 'result_infos/create'
  resources :result_infos
  resources :subject_infos
  resources :exam_infos
  post 'attendence_infos/update'
  resources :attendence_infos
  resources :class_infos
  resources :student_infos

end

app/models/attendence_info.rb
class AttendenceInfo < ActiveRecord::Base
end

app/controllers/attendence_infos_controller.rb
class AttendenceInfosController < ApplicationController
  before_action :set_attendence_info, only: [:edit, :destroy]
  skip_before_filter :verify_authenticity_token
  # GET /attendence_infos
  # GET /attendence_infos.json
  def index
    @attendence_infos = AttendenceInfo.order('record_date').all
  end

  # GET /attendence_infos/1
  # GET /attendence_infos/1.json
  def show
    @students = StudentInfo.where(referenced_class_id: params[:id]).all
  #puts YAML::dump(@students)
  end

  # GET /attendence_infos/new
  def new
    @attendence_info = AttendenceInfo.new
  end

  # GET /attendence_infos/1/edit
  def edit
  end

  # POST /attendence_infos
  # POST /attendence_infos.json
  def create
    @attendence_info = AttendenceInfo.new(attendence_info_params)

    respond_to do |format|
      if @attendence_info.save
        format.html { redirect_to @attendence_info, notice: 'Attendence info was successfully created.' }
        format.json { render :show, status: :created, location: @attendence_info }
      else
        format.html { render :new }
        format.json { render json: @attendence_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendence_infos/1
  # PATCH/PUT /attendence_infos/1.json
  def update
    puts "================================="
    puts YAML::dump(params)
    puts "================================="
    params.each do |key,value|
      if (key.is_a? String)
        if(key.first == 's' )
          name = ""
          name << key
          name[0]= ''
          puts "Yessss"
          student_id_absent = name.to_i
          puts "id="
          puts student_id_absent
          old_record = AttendenceInfo.where(:student_id => student_id_absent).all.where(:record_date => params[:record_date]).all
#          puts "OLD RECORD = "
#          puts YAML::dump(old_record)
          puts "old_record.size = "
          puts old_record.size
          if old_record != nil && old_record.size > 0
            puts "Already present"
          else
            a = AttendenceInfo.new
            a.student_id = student_id_absent
            a.record_date = params[:record_date]
            a.status = "Absent"
            a.save!
            puts "Supposed to Save"
          end

        else
          puts "Noooo"
        end
      else
        puts "Noooo22222"
      end
    end
    redirect_to attendence_infos_url
  #respond_to do |format|
  #  if @attendence_info.update(attendence_info_params)
  #    format.html { redirect_to @attendence_info, notice: 'Attendence info was successfully updated.' }
  #    format.json { render :show, status: :ok, location: @attendence_info }
  #  else
  #    format.html { render :edit }
  #   format.json { render json: @attendence_info.errors, status: :unprocessable_entity }
  # end
  #end
  end

  # DELETE /attendence_infos/1
  # DELETE /attendence_infos/1.json
  def destroy
    @attendence_info.destroy
    respond_to do |format|
      format.html { redirect_to attendence_infos_url, notice: 'Attendence info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendence_info
    @attendence_info = AttendenceInfo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attendence_info_params
    params.require(:attendence_info).permit(:student_id, :class_id, :status, :record_date)
  end
end

app/helpers/attendence_infos_helper.rb
module AttendenceInfosHelper
end

app/views/attendence_infos/_form.html.erb
<%= form_for(@attendence_info) do |f| %>
  <% if @attendence_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendence_info.errors.count, "error") %> prohibited this attendence_info from being saved:</h2>

      <ul>
      <% @attendence_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :class_id %><br>
    <%= f.text_field :class_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status, options_for_select([['ABSENT','ABSENT'], ['PRESENT','PRESENT']])) %>
  </div>
  <div class="field">
    <%= f.label :record_date %><br>
    <%= f.date_select :record_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendence_infos/edit.html.erb
<h1>Editing Attendence Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendence_info %> |
<%= link_to 'Back', attendence_infos_path %>

app/views/attendence_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendence Infos</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Class</th>
      <th>Status</th>
      <th>Record date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendence_infos.each do |attendence_info| %>
      <tr>
        <td><%= attendence_info.student_id %></td>
        <td><%= attendence_info.class_id %></td>
        <td><%= attendence_info.status %></td>
        <td><%= attendence_info.record_date %></td>
        <td><%= link_to 'Show', attendence_info %></td>
        <td><%= link_to 'Edit', edit_attendence_info_path(attendence_info) %></td>
        <td><%= link_to 'Destroy', attendence_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendence info', new_attendence_info_path %>

app/views/attendence_infos/new.html.erb
<h1>New Attendence Info</h1>

<%= render 'form' %>

<%= link_to 'Back', attendence_infos_path %>

app/views/attendence_infos/show.html.erb
<p id="notice"><%= notice %></p>
<form action="update" method="post">
<td>
  <strong>Record date:</strong>
  <%= date_field_tag :record_date %>
</td>
<table>
<thead><tr><th>Roll No</th><th>Name</th><th>Is Absent</th></tr></thead>
<tbody>
<% @students.each do |s|%>
<tr>
<td>
  <%= s.student_id %>
</td>

<td>
  <%= s.student_name %>
</td>
<td>
  <%= check_box_tag 's'+s.student_id.to_s%>
</td>
</tr>
<% end %>
</tbody></table>
<%= submit_tag  "Record Attendance"%>
</form>
<p><p>
<%= link_to 'Back', attendence_infos_path %>